sudo: false
language: python
python:
  - 2.7

services: postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE perdiem;" -U postgres

script:
  - cd perdiem
  - python manage.py migrate
  - python manage.py collectstatic --no-input
  - coverage run ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
